name: Build

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  build_android:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Node.js
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Download NDK r17b
        run: |
          curl -o android-ndk-r17b-linux-x86_64.zip https://dl.google.com/android/repository/android-ndk-r17b-linux-x86_64.zip
          unzip android-ndk-r17b-linux-x86_64.zip -d $HOME/android-ndk
          rm android-ndk-r17b-linux-x86_64.zip

      - name: Set NDK path
        run: |
          echo "NDK_HOME=$HOME/android-ndk/android-ndk-r17b" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r17b" >> $GITHUB_ENV
          echo "ndk.dir=$HOME/android-ndk/android-ndk-r17b" > telon-gateway-app/android/local.properties

      - name: Verify NDK installation
        run: |
          echo "NDK_HOME=$NDK_HOME"
          ls -la $NDK_HOME

      - name: Install Dependencies
        run: npm ci
        working-directory: telon-gateway-app

      - name: Bundle React Native JavaScript
        run: |
          mkdir -p android/app/build/intermediates/assets/release/
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/build/intermediates/assets/release/index.android.bundle \
            --assets-dest android/app/build/intermediates/res/merged/release
        working-directory: telon-gateway-app

      - name: Build Android Release AAB
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease -Pkeystore.password=${{ secrets.KEYSTORE_PASSWORD }}
        working-directory: telon-gateway-app

  download_bundle:
    runs-on: ubuntu-latest
    needs: build_android

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy and Archive Android App Bundle
        run: |
          mkdir -p dist
          cp android/app/build/outputs/bundle/release/app-release.aab dist/
        working-directory: telon-gateway-app

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-bundle
          path: telon-gateway-app/dist
